### ISSUE TITLE
Tags cannot be edited in Chrome on edX (prompt blocked)

### ISSUE THREAD

**Issue by ChristopherChudzicki** [SketchResponse/sketchresponse#38]
@jmclaus @msegado @jefrench Tags are working fine for me locally in both Safari and Chrome. But on edX in Chrome Version 59.0.3071.115, edX blocks the `prompt()`:

`main.js:33 Ignored call to 'prompt()'. The document is sandboxed, and the 'allow-modals' keyword is not set.`

Safari seems to allow the prompt in edX, though.

To some extent I think this is an edX issue—their jsinput iframe should allow modals if authors can put javascript elsewhere in the course.

**Comment by jefrench** [comment]
Let's do it!

**Comment by jmclaus** [comment]
@ChristopherChudzicki @jefrench @msegado @brian-french 

I actually used this instead:

https://github.com/limonte/sweetalert2
https://www.npmjs.com/package/sweetalert2

Turned out to be easier to use & integrate than vex.

I opened a new PR where the JS system prompt has been replaced by a SweetAlert2 popup window. And tested it in Studio & LMS, works like a charm.

https://github.com/SketchResponse/sketchresponse/pull/42
